void nrerror();
float *vector();
int *ivector();
unsigned char *cvector();
unsigned long *lvector();
double *dvector();
float  **matrix();
double **dmatrix();
int    **imatrix();
float  ***f3tensor();
double  ***d3tensor();
void free_vector();
void free_ivector();
void free_cvector();
void free_lvector();
void free_dvector();
void free_matrix();
void free_dmatrix();
void free_imatrix();
void free_f3tensor();
void free_d3tensor();
